# Generated by Django 6.0.2 on 2026-02-23 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherrecord',
            name='temperature_api2',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
